# hugo server --themesDir ... --baseURL=http://0.0.0.0:1313/example

baseURL: https://solareenlo.com/
title: SOLAREENLO
theme: book
disableKinds: ["taxonomy", "taxonomyTerm"]
# themesDir: ../..

# Book configuration
disablePathToLower: true
enableGitInfo: true

# Code highlight
pygmentsStyle: solarized-dark
# pygmentsStyle: molekai;
pygmentsCodeFences: true

params:
  # (Optional, default true) Show or hide table of contents globally
  # You can also specify this parameter per page in front matter
  BookShowToC: true

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  BookMenuBundle: /menu

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection: docs

  # This value is duplicate of $link-color for making active link highlight in menu bundle mode
  BookMenuBundleActiveLinkColor: \#004ed0

  # Include JS scripts in pages. Disabled by default.
  # - Keep side menu on same scroll position during navigation
  BookEnableJS: true

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo: https://github.com/solareenlo/blog-hugo

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  BookEditPath: edit/master/content

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat: "Jan 2, 2006"

# リンクを別タグで開くには下の2行をコメントアウトを外せば良い.
# blackfriday:
#   hrefTargetBlank: true
