# hugo server --themesDir ... --baseURL=http://0.0.0.0:1313/example

baseURL: https://solareenlo.com/
title: solareenlo
# theme: book-ori
theme: book-fork
# thema: hugo-book
# disableKinds: ["taxonomy", "taxonomyTerm"]
# themesDir: ../..

# Book configuration
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

# Code highlight
pygmentsStyle: solarized-dark
# pygmentsStyle: solarized-dark256
# pygmentsStyle: solarized-light
# pygmentsStyle: molekai
pygmentsCodeFences: true

menu:
  before: []
  after:
    - name: "Github"
      url: "https://github.com/solareenlo/"
      weight: 20
    - name: "Twitter"
      url: "https://twitter.com/solareenlo/"
      weight: 30

params:
  # (Optional, default 6) Set how many table of contents levels to be showed on page.
  # Use false to hide ToC, note that 0 will default to 6 (https://gohugo.io/functions/default/)
  # You can also specify this parameter per page in front matter
  BookToC: 3

  # (Optional, default true) Show or hide table of contents globally
  # You can also specify this parameter per page in front matter
  BookShowToC: true

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  # BookMenuBundle: /menu

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection: docs

  # This value is duplicate of $link-color for making active link highlight in menu bundle mode
  BookMenuBundleActiveLinkColor: \#004ed0

  # Include JS scripts in pages. Disabled by default.
  # - Keep side menu on same scroll position during navigation
  BookEnableJS: true

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo: https://github.com/solareenlo/blog-hugo

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  BookEditPath: edit/master/content

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat: "Jan 2, 2006"

  # (Optional, default true) Enables search function with lunr.js,
  # Index is built on fly, therefore it might slowdown your website.
  BookSearch: true

  # (Optional, default true) Enables comments template on pages
  # By default partals/docs/comments.html includes Disqus template
  # See https://gohugo.io/content-management/comments/#configure-disqus
  # Can be overwritten by same param in page frontmatter
  BookComments: true

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables portable links and link checks in markdown pages.
  # Portable links meant to work with text editors and let you write markdown without {{< relref >}} shortcode
  # Theme will print warning if page referenced in markdown does not exists.
  BookPortableLinks: true

  # (Optional, default none) Search config for flexsearch index.
  # Read documentation at https://github.com/nextapps-de/flexsearch#usage. By default 'balance' preset is used.
  # This option allows to set specific configs for languages support. Must be valid JavaScript object.
  BookSearchConfig: |
    { cache: true }

# リンクを別タグで開くには下の2行をコメントアウトを外せば良い.
# blackfriday:
#   hrefTargetBlank: true
