version: '3'
services:
  hugo:
    image: solareenlo/alpine-hugo:latest
    build: .
    command: "hugo server --bind 0.0.0.0 -D --cleanDestinationDir --disableFastRender"
    volumes:
      - ./:/src
      - ./public/:/output
    environment:
      - HUGO_REFRESH_TIME=3600
      # - HUGO_THEME=book-fork
      - HUGO_BASEURL=https://solareenlo.com/
    restart: always
    ports:
      - "1313:1313"
